// <auto-generated />
namespace PassionProject_RecipeBookApp_AkshayaDupati.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class recipeingredient1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(recipeingredient1));
        
        string IMigrationMetadata.Id
        {
            get { return "202206211235466_recipeingredient1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
